name: Publish Docker Container

on:
  push:
    tags:
      - 'web-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Add DevExpress Key
      run: export DEVEXPRESS_NUGET_KEY=${{ secrets.DEVEXPRESS_NUGET_KEY }}
    - name: checkout branch
      uses: actions/checkout@v3
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Build the Docker image and tag
      run: DOCKER_BUILDKIT=1 docker build --secret id=DEVEXPRESS_NUGET_KEY,env=DEVEXPRESS_NUGET_KEY -f COMETwebapp/Dockerfile -t rheagroup/comet-web-community-edition:latest -t rheagroup/comet-web-community-edition:${{ steps.vars.outputs.tag }} .
    - name: push $RELEASE_VERSION tag
      run: docker push rheagroup/comet-web-community-edition:${{ steps.vars.outputs.tag }}
    - name: push latest tag
      run: docker push rheagroup/comet-web-community-edition:latest